export { sendLeadToCrm, updateLeadInCrm, createClientInCrm, updateClientInCrm, createConversationInCrm, addLeadToAttendanceQueue, registerCampaignOrigin, syncLeadStatus } from './crm/erpBridge'
export { afterCrmLeadSynced, upsertCrmErpSync, COL_CRM_ERP_SYNC } from './crm/crmSync'
export type { ErpLeadPayload, CrmLeadPayload, CrmClientPayload, CrmConversationPayload, LeadSyncResult } from './crm/types'
export { erpMockAdapter } from './adapters/erpMockAdapter'
export { getErpAdapter, getNxErpHealthAdapter, selectErpAdapter } from './adapters/erpProvider'
export { nxErpAdapter, createNxErpAdapter } from './adapters/nxErpAdapter'
export { crmAdapter, getCrmAdapter } from './adapters/crmAdapter'
export * from './events'
export { getNxErpCampaignAdapter, UnconfiguredNxErpCampaignAdapter } from './nxErpCampaign'
